### ISSUE TITLE
Fix / Write documentation

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/insim.rs#23]
- [x] Review all documentation after the great crate split in #31 
- [x] Review all documentation after the expunging of insim::Client #59 
- [x] Review all documentation after adding UDP support #63
