### ISSUE TITLE
Insim v9 Support - Tracking Issue

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/insim.rs#4]
https://www.lfs.net/forum/thread/95662-New-InSim-packet-size-byte-and-mod-info

This issue is a living document until v9 is launched.

- [x] Either patch `tokio_util::codec::length_delimited::LengthDelimitedCodec` to allow the 1/4th packet size (probably a closure or something), or reimplement LengthDelimitedCodec specifically for our purposes. Latter is probably easier.
- [x] ~~IS_AXM maximum objects increased to 60 (was 30) - see AXM_MAX_OBJECTS~~ - packet isn't implemented, but we generally don't care about this anyway
- [x] ~~IS_MCI maximum cars increased to 16 (was 8) - see MCI_MAX_CARS~~ - code already handles this
- [x] Skin ID for MOD vehicles in the CName fields
